apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep3pod-blk
  labels:
    app: dep3pod-blk
spec:
  replicas: 3              ## 3개의 파드 기동
  selector:
    matchLabels:
      app: dep3pod-blk
  template:
    metadata:
      labels:
        app: dep3pod-blk
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        volumeMounts:
        - name: blk
          mountPath: /mnt
        command: ["/usr/bin/tail","-f","/dev/null"]
      volumes:              ## 파드의 볼륨 정의
      - name: blk
        persistentVolumeClaim:
          claimName: bronze-blk
