role-base-access-ctl.yml
# 클러스터 롤
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodes
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","delete"]
---
# 클러스터롤과 서비스 어카운트의 바인딩
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodes
subjects:
- kind: ServiceAccount
  name: high-availability  # 서비스 어카운트 이름
  namespace: tkr-system    # 네임스페이스 지정은 필수
roleRef:
  kind: ClusterRole
  name: nodes
  apiGroup: rbac.authorization.k8s.io
